/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        secondary: '#006b5f',
        'surface-container': '#e9edff',
        error: '#ba1a1a',
        'primary-fixed-dim': '#3de273',
        'tertiary-fixed': '#a8f0e3',
        'outline-variant': '#bbcbb9',
        'error-container': '#ffdad6',
        'surface-bright': '#f9f9ff',
        'surface-container-low': '#f1f3ff',
        'primary-container': '#25d366',
        'on-error': '#ffffff',
        'on-background': '#141b2b',
        'secondary-fixed-dim': '#72d8c8',
        'inverse-on-surface': '#edf0ff',
        'on-secondary-container': '#006f64',
        'on-tertiary-fixed': '#00201c',
        'surface-variant': '#dce2f7',
        'on-secondary-fixed-variant': '#005047',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#00201c',
        'inverse-surface': '#293040',
        'on-primary-fixed-variant': '#005322',
        'inverse-primary': '#3de273',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#dce2f7',
        background: '#f9f9ff',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#005523',
        'on-tertiary-fixed-variant': '#005047',
        'tertiary-fixed-dim': '#8cd4c7',
        tertiary: '#1c695f',
        'surface-tint': '#006d2f',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#002109',
        surface: '#f9f9ff',
        'on-tertiary-container': '#005249',
        'on-surface-variant': '#3c4a3d',
        'on-surface': '#141b2b',
        'surface-container-high': '#e1e8fd',
        'on-primary': '#ffffff',
        'tertiary-container': '#7ec5b8',
        'secondary-container': '#8cf1e1',
        primary: '#006d2f',
        'secondary-fixed': '#8ff4e3',
        'primary-fixed': '#66ff8e',
        outline: '#6c7b6b',
        'surface-dim': '#d3daef',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        xs: '4px',
        gutter: '24px',
        lg: '24px',
        xl: '32px',
        unit: '4px',
        xxl: '48px',
        'margin-mobile': '16px',
        md: '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'body-sm': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
